name: update-vestaboard

on:
  schedule:
    - cron: '*/5 * * * *' # Runs the workflow every 5 minutes

jobs:
  update-vestaboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          node-version: 20 # Update to Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          node-version: 20 # Update to Node.js 20

      - name: Install dependencies
        run: |
          npm install @sanity/client

      - name: Update Vestaboard
        run: |
          YOUR_SANITY_API_URL="https://your-sanity-api-url.com" # Replace with your Sanity API URL
          YOUR_VESTABOARD_API_KEY="YOUR_API_KEY" # Replace with your Vestaboard API Key

          # Get the most recent launch information from Sanity
          LAUNCH_INFO=$(node get-launch-info.js "$YOUR_SANITY_API_URL")

          # Format the launch information for Vestaboard
          FORMATTED_MESSAGE=$(node format-message.js "$LAUNCH_INFO")

          # Send the formatted message to Vestaboard
          curl -X POST -H "X-Vestaboard-Read-Write-Key: $YOUR_VESTABOARD_API_KEY" -H "Content-Type: application/json" -d "$FORMATTED_MESSAGE" https://rw.vestaboard.com/

        env:
          YOUR_SANITY_API_URL: ${{ secrets.SANITY_API_URL }} # Store your Sanity API URL as a secret in your repository settings
          YOUR_VESTABOARD_API_KEY: ${{ secrets.VESTABOARD_API_KEY }} # Store your Vestaboard API Key as a secret in your repository settings
