name: update-vestaboard

on:
  push:
    branches:
      - main

jobs:
  update-vestaboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Use setup-node action
        with:
          node-version: '14'  # Specify Node.js 14 (compatible with Node.js 20)

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Fetch all launch information
        run: |
          python main.py fetch-launches
          echo "::set-output name=message-layout::$(cat message_layout.json)"
      
      - name: Save message layout array
        run: echo '${{ toJson(steps.create-message-layout.outputs.message-layout) }}' > message_layout.json
      
      - name: Send message to Vestaboard
        run: python main.py send-to-vestaboard
        env:
          VESTABOARD_API_KEY: ${{ secrets.VESTABOARD_API_KEY }}
      
      - name: Print message layout array
        run: cat message_layout.json
