name: update-vestaboard

on:
  schedule:
    - cron: '0 * * * *'   # At the top of the hour
    - cron: '20 * * * *'  # At 20 minutes past the hour
    - cron: '40 * * * *'  # At 40 minutes past the hour
  workflow_dispatch:

jobs:
  update-vestaboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python main.py
        env:
          SANITY_API_URL: ${{ secrets.SANITY_API_URL }}
          VESTABOARD_API_KEY: ${{ secrets.VESTABOARD_API_KEY }}
